# -*- coding: utf-8 -*-
"""CDC Github Clone Ex 3 Final Submission BD.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14ifTIZLA65KnCDEsWdwlO085JVuXgrvF
"""

# Covid-19 Genomic Dataset Example 3:
# CDC Github clone Dataset
# This dataset provides detailed information on SARS-CoV-2 variants and their surveillance
# across U.S. states. It includes variant names, lineages, state populations, and
# reporting periods. It also tracks COVID-19 case counts, including positive cases
# reported to the U.S. Department of Health & Human Services. Key data includes
# weekly statistics, such as the number of positive cases and total reported cases,
# along with the population of each state, which is essential for understanding the
# spread of different variants over time.

# Commented out IPython magic to ensure Python compatibility.
# Clone the repository
!git clone https://github.com/CDCgov/SARS-CoV-2_Genomic_Surveillance.git

# Change directory to the 'Code' folder inside the repository
# %cd SARS-CoV-2_Genomic_Surveillance/Code

# List files to check the available code
!ls

import pandas as pd

# Read CSV
df = pd.read_csv('example_data.csv')

# Display the first few rows of the dataframe
df.head()

# Check data types and look for null values
df.info()

# Summary statistics for numerical columns
df.describe()

# Column names
print(df.columns)

# Check for missing values
df.isnull().sum()